<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Back to modules' => '',
    '<strong>Bookmark</strong> module configuration' => 'Configuration du module de <strong>signet</strong>',
    'Bookmark view settings' => 'Paramètres de vue des signets',
    'Here you can change the view settings for bookmarks.' => 'Ici, vous pouvez modifier les paramètres d\'affichage des signets.',
    'Show Bookmark-Count in braces.' => 'Afficher le compte des signets dans les appareils orthopédiques.',
    'Show global Bookmark-View in full width.' => 'Affichez le signet global en pleine largeur.',
    'Show pinned content first.' => 'Montrer le contenu en premier.',
];
