<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Select color' => '',
    '<strong>Bookmark</strong> module configuration' => '<strong>Lesezeichen</strong> Modul-Konfiguration',
    'Back to modules' => 'Zurück zu den Modulen',
    'Bookmark view settings' => 'Lesezeichen Ansichts-Einstellungen',
    'Here you can change the view settings for bookmarks.' => 'Hier kannst du die Ansichts-Einstellungen für Lesezeichen anpassen.',
    'Icon color' => 'Symbol-Farbe',
    'Show Bookmark-Count in braces.' => 'Zeige Anzahl gesetzter Lesezeichen in Klammern.',
    'Show an icon for each entry.' => 'Für jeden Eintrag ein Symbol anzeigen.',
    'Show global Bookmark-View in full width.' => 'Zeige globale Lesezeichen-Ansicht in voller Breite.',
    'Show pinned content first.' => 'Zeige angeheftete Beiträge zuerst.',
    'Sort order' => 'Sortierung',
    'Keep bookmarks private and do not send notifications.' => 'Lesezeichen privat halten und keine Benachrichtigungen senden.',
];
